name: Reusable Release
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: true
        description: "Tags to push the bundle with, e.g. 'latest v1.0.0'"
      push_legacy_bundle:
        type: boolean
        required: false
        default: false
        description: "Push legacy 'trivy-policies' bundle to ghcr.io (for backwards compatibility)"

env:
  GH_USER: aqua-bot
  AQUA_DOCKERHUB_REPO: aquasec

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create bundle
        run: make bundle

      - name: setup-oras
        uses: oras-project/setup-oras@v1.2.2

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER || env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy policy bundle to ghcr.io (for backwards compatibility)
        if: ${{ inputs.push_legacy_bundle }}
        run: |
          tags=(${{ inputs.tags }})
          for tag in ${tags[@]}; do
              echo "Pushing artifact with tag: ${tag}"
              oras push ghcr.io/${{ github.event.repository.owner.name }}/trivy-policies:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              --annotation "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
              --annotation "org.opencontainers.image.revision=$GITHUB_SHA" \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done

      - name: Deploy checks bundle to registries
        run: |
          tags=(${{ inputs.tags }})
          registries=(
            "ghcr.io/${{ github.repository }}"
            "${{ vars.DOCKERHUB_REPOSITORY || env.AQUA_DOCKERHUB_REPO }}/${{ github.event.repository.name }}"
          )
          for registry in ${registries[@]}; do
            for tag in ${tags[@]}; do
              echo "Pushing artifact to ${registry}:${tag}"
              if oras push ${registry}:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip; then
                echo "Successfully pushed artifact to ${registry}:${tag}"
              else
                echo "Failed to push artifact to ${registry}:${tag}"
                exit 1
              fi
            done
          done

      - name: Microsoft Teams Notification
        ## Until the PR with the fix for the AdaptivCard version is merged yet
        ## https://github.com/Skitionek/notify-microsoft-teams/pull/96
        ## Use the aquasecurity fork
        uses: aquasecurity/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.TRIVY_MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
