name: test rego
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  merge_group:
env:
  GO_VERSION: "1.21"
jobs:
  opa-tests:
    name: OPA tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OPA Format
        run: |
          files=$(opa fmt --list . | grep -v vendor || true)
          if [ -n "$files" ]; then
            echo "=== The following files are not formatted ==="
            echo "$files"
            exit 1
          fi

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test Rego checks
        run: make test-rego